### Your exercise is to speed it up using NumPy, avoiding explicit loops 
• Hint: Use np.searchsorted and np.cumsum 

If you can, implement the functionality as a class called discreteRV, where 

• the data for an instance of the class is the vector of probabilities q 

• the class has a draw() method, which returns one draw according to the algorithm described above 

If you can, write the method so that draw(k) returns k draws from q

In [118]:
import numpy as np

In [66]:
q = np.array([0.5,0.2,0.3])

In [103]:
qcum = q.cumsum()

In [104]:
qcum

array([0.5, 0.7, 1. ])

In [144]:
np.searchsorted(q.cumsum(),uniform(0,1))

1

In [70]:
from random import uniform 
def sample(q): 
    a = 0.0 
    U = uniform(0, 1) 
    for i in range(len(q)): 
        if a < U <= a + q[i]: 
            return i 
        a = a + q[i]

In [127]:
sample(q)

2

In [187]:
class discreteRV:
    def __init__(self,q):
        self.q = np.array([0.5,0.2,0.3])
    def draw(self):
        print(np.searchsorted(q.cumsum(),uniform(0,1)))


In [222]:
q = np.array([0.5,0.3,0.3])
obj = discreteRV(q)
obj.q

array([0.5, 0.2, 0.3])

array([0.5, 0.2, 0.3])