In [239]:
import re
import numpy as np


file = open("graph.txt")
graph = []
for i in file:
    entry = i.rstrip().split(sep=',')
#     print(entry)
    # process 'node0, node1 0.04, node8 11.11, node14 72.21'
    # into dictionary in graph[0]
    node_dict= {}
    for i in range(1,len(entry)):
#     print(entry[i])
        m = re.search('(node\d+) ([\d\.]+)', entry[i])
        if m is not None:
            node_dict[m.group(1)] = float(m.group(2))
    graph.append(node_dict)

In [255]:
aa = J.copy()
aa

array([1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 2.56412e+03, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10,
       1.00000e+10, 1.00000e+10, 1.00000e+10, 1.00000e+10, 2.478

In [278]:
M = 1e10
lastnode = 99

J = np.full(len(graph), M)
J[lastnode] = 0




while True:
    old_J = J.copy() 
    for i,val in enumerate(J):
        if i != lastnode:
            next_J = J[i]
            for key,value in graph[i].items():
                reachable_point = int(re.search("node(.*)",key).group(1))
                next_J = min(value + J[reachable_point], next_J)
#             print(i, next_J)
            J[i] = next_J

    if all(old_J == J): 
        break


In [279]:
J[0:5]

array([160.55, 162.26,  88.52, 143.73, 145.12])

In [280]:
J[95:]

array([0.27, 1.06, 0.63, 0.33, 0.  ])